name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e04880b15ad5a2c1b9d52e45a519ea4ae5ab3238d47412b6e577219db8525dd9"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
