name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1668a3b970bf5cb29d32eb5cbe2bf44cc6a1c72cd68767fa8f2dc6a404e33ae4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
