name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd15efb84525ac6674a20139bf52a7d47db14264a96c18f61a0973ac1aa4a88f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
