name = "Coolpack"
author = "abc and nicky"
version = "1.0.2a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b182b77f8f9abede49ad29b35346e05d4aef3bc60c9085ea7aadc34d5f1f67a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
