name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "011284f2545dbd4b35f2a360e58ef83e8e6c2e34e76949d68a825a1474902672"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
