name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f46e58be0f4a18a15b097a7a09725defb5e8e3f4be6558714f09b5139560f17"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
