name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e660c5d4350f35ee208cf58b15d90bf84430a80f5c57018c33ddb852faddec0d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
