name = "Coolpack"
author = "abc and nicky"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb4a316cc06ebda2742b1d26731f2dac82903ab4424ad6b7e1771fa673598d57"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
