name = "Coolpack"
author = "abc and nicky"
version = "1.0.2a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d80d3004c3758d3ea7a3588009b38b2aaadfdd99b343ab1d10a814393611d48"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
