name = "Coolpack"
author = "abc and nick"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebcaea0c559aca8f0e1da793b08baae450d896f16a9ff3dcb2af20c3e7761e20"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
