name = "Coolpack"
author = "abc and nick"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1f8990085a20ce4968bff7df7d575ba8000a09f02edd739444d0ec8ccb5fcd2"

[versions]
fabric = "0.19.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
