name = "Coolpack"
author = "abc and nick"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb72ad166b6c4eb8bc924a64d12ba1186c191edace377c4f43564bc7819cd1ae"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
