name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31a209fdbdb3085e18929452341c625df617496a150951a37b4c9c9162370bda"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
