name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "578a6a9bb450d2be55df5211e2a625c0092e8dcdfba014fac9f2f1277720f2b5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
