name = "Coolpack"
author = "abc and nicky"
version = "1.0.2a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "792037b218d2aaaf52916b85f3aa137884f06b1e2883d58d559f286868940279"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
