name = "Coolpack"
author = "abc and nick"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29502aa290033ae8196f2e1790de9cf167608c51d366f3b0f5352c5f1e45d4d4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
