name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84ed0956192e489706b6fc109dc8c3b5ad3786a599dfe0a77fdf28d763f939f7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
