name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b0c49c7f57683a851b40ce308ba23adfdd11fcf4cae85be2a65dbec716039d6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
