name = "Coolpack"
author = "abc and nicky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45c85479619b86045699c6e9e13ce665a4aa6a4b97bcf5c9073f585abf668833"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
