name = "Coolpack"
author = "abc and nicky"
version = "1.0.0-a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7bbd38308679fefe94d483d15815e7aa59c7bb70fb1d280e18647f18e0147ca"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
